name: 'Build Plugin'
description: ''
inputs:
  filename:
    required: false
    default: ${{ github.event.repository.name }}
  discord_webhook_url:
    required: false
  libs_dir:
    required: false
    default: "lib"
  regex:
    required: false
  exclude_defaults:
    required: false
  dirs:
    required: false
  files:
    required: false

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      shell: bash
      run: |
        uv pip install -r ./requirements.txt --target ./lib
    
    - name: Update Version
      if: ${{ github.event_name != 'release' }}
      shell: bash
      run: |
        uv run https://raw.githubusercontent.com/cibere/FlowBuildPluginAction/refs/heads/master/update_version.py ${{ github.sha }}
    
    - name: Build Archive
      shell: bash
      run: |
        uv run https://raw.githubusercontent.com/cibere/FlowBuildPluginAction/refs/heads/master/build_plugin.py ${{ inputs.filename }}.zip --included-directories "${{ inputs.dirs }}" --included-files "${{ inputs.files }}" --regex "${{ inputs.regex }}" --exclude-defaults "${{ inputs.exclude_defaults }}" --lib-directory "${{ inputs.libs_dir }}"

    - name: Extract Archive To Dist
      shell: bash
      run: |
        mkdir dist
        unzip -q ${{ inputs.filename }}.zip -d dist

    - name: Upload Archive to workflow artifacts
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist
        name: ${{ inputs.filename }}
        compression-level: 0
    
    - name: Send Artifact Download Url To Webhook
      uses: tsickert/discord-webhook@v6.0.0
      if: ${{ inputs.discord_webhook_url != '' }}
      with:
        webhook-url: ${{ inputs.discord_webhook_url }}
        content: https://github-artifact-downloader.cibere.dev/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ steps.upload-artifact.outputs.artifact-id }}/${{ inputs.filename }}.zip

    - name: Upload Archive to release artifacts
      uses: softprops/action-gh-release@v2
      if: ${{ github.event_name == 'release' }}
      with:
        files: ${{ inputs.filename }}.zip
    
    - name: Display Download Url
      shell: bash
      run: echo https://github-artifact-downloader.cibere.dev/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ steps.upload-artifact.outputs.artifact-id }}/${{ inputs.filename }}.zip